# Generated by Django 5.1.4 on 2024-12-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0002_delete_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
                ("route", models.JSONField()),
            ],
        ),
    ]
